### PR TITLE
Added function Test-ADGroupMembership

### PR DESCRIPTION
**Pull request by powershellking**
Before submitting this Pull Request, I made sure:

- [X] I tested the toolkit with my changes and made sure it doesn't break other code.

- [X] I updated the documentation with the changes I made.

- [X] The code I changed has comments with explanation.

- [X] The encoding of the file wasn't changed. It is still UTF8 with BOM.

This pull request contains the function requested in #638

### CODE REVIEW

**Comment by luki1412** [comment]
Is there any benefit of using this method over https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.directorysearcher

**Comment by powershellking** [comment]
As I understand, when using the directory searcher you'll have to specify a LDAP path where to search. The way I implemented it doesn't require specifying a search root so you don't have to care about in which OU the user and group object are located.

**Comment by luki1412** [comment]
> As I understand, when using the directory searcher you'll have to specify a LDAP path where to search. The way I implemented it doesn't require specifying a search root so you don't have to care about in which OU the user and group object are located.

No, you only need a filter. It also supports older net framework versions. It can return a lot of data about the user you specify, unless you only tell it to select certain properties so it could also serve as AD data retrieval function.

**Comment by seanlillis** [comment]
The team have reviewed this pull request and have decided to reject it as this class is known to be buggy.

**Pull request closed without merging**
