### PR TITLE
Version bump to 3.8.3

### PR DESCRIPTION
**Pull request by luki1412**
Version bump. 
Updates changelog with missing entries.

### CODE REVIEW

**Comment by ocsscott** [comment]
will there be a MSI release of 3.8.3?

________________________________

**Comment by luki1412** [comment]
No. The toolkit is meant to be redistributed so there is no reason, I can see ,to have it as an MSI. Do you need it in an MSI?

**Comment by ocsscott** [comment]
no even a zip just all the latest files all together would be nice

________________________________

**Comment by luki1412** [comment]
We always do a nice zip. Don't worry.

**Comment by ocsscott** [comment]
is the zip for 3.8.3 ready yet or still testing?

________________________________

**Comment by luki1412** [comment]
It will be released when it's ready.

**Review by sintaxasn — APPROVED** [review]

**Pull request merged**
