### PR TITLE
Set-ActiveSetup / Execute-ProcessAsUser fixes

### PR DESCRIPTION
**Pull request by DanGough**
# Pull Request

## Description

Fixes: #999 

### Bugs fixed:
- When Set-ActiveSetup was called with the StubPath being a direct path to a .ps1 file, it would fail to execute for the current user.
- Execute-ProcessAsUser incorrectly processed arguments when the main exe being called was cmd.exe; double quotes " were being replaced by ^".

### Enhancements:
- Set-ActiveSetup now injects wscript.exe into the StubPath instead of cscript.exe when passed a .vbs file. It makes sense to do so seeing how it goes to great lengths to ensure that any any .ps1 / .cmd files are run hidden.
- Set-ActiveSetup now supports .bat files (handled in the same way as .cmd files)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] General code cleanup (non-breaking change which improves readability)

## Checklist

- [x] I am pulling to the **develop** branch
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have tested my changes to prove my fix is effective
- [x] I have made sure that any script file-encoding is set to UTF8 with BOM, i.e. unchanged.

## How Has This Been Tested?

Create the following test scripts under C:\Temp:

**Say Hello.ps1:**
```powershell
Add-Type -AssemblyName System.Speech; $speak = New-Object System.Speech.Synthesis.SpeechSynthesizer; $speak.Speak('Hello')
```

**Say Hello.cmd: / Say Hello.bat:**
```vbscript
PowerShell -Command "Add-Type -AssemblyName System.Speech; $speak = New-Object System.Speech.Synthesis.SpeechSynthesizer; $speak.Speak('Hello')"
```

**Say Hello.vbs:**
```batch
Set sapi = CreateObject("SAPI.SpVoice")
sapi.Speak "Hello"
```

Then running any of the commands below should execute the script hidden, producing speech:

```powershell
Set-ActiveSetup -Key 'Test' -PurgeActiveSetupKey; Set-ActiveSetup -Key 'Test' -StubExePath 'C:\Temp\Say Hello.ps1'
Set-ActiveSetup -Key 'Test' -PurgeActiveSetupKey; Set-ActiveSetup -Key 'Test' -StubExePath 'C:\Temp\Say Hello.cmd'
Set-ActiveSetup -Key 'Test' -PurgeActiveSetupKey; Set-ActiveSetup -Key 'Test' -StubExePath 'C:\Temp\Say Hello.bat'
Set-ActiveSetup -Key 'Test' -PurgeActiveSetupKey; Set-ActiveSetup -Key 'Test' -StubExePath 'C:\Temp\Say Hello.vbs'
```

### CODE REVIEW

**Comment by DanGough** [comment]
@mmashwani I'd appreciate your review here particularly around the change to RunHidden.vbs!

**Comment by DanGough** [comment]
> We're changing all the commits on our PSADT Files, but it's not working. It only works if the path to activesetup.cmd has no spaces. We believe this is an issue of quotes being passed from the powershell script to the vbs script.

This scenario was tested in the example I gave above:

```powershell
Set-ActiveSetup -Key 'Test' -PurgeActiveSetupKey; Set-ActiveSetup -Key 'Test' -StubExePath 'C:\Temp\Say Hello.cmd'
```

Are you using similar syntax or something different?

Also please ensure you are using this branch:

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/DanGough/issue999

In Zip form:

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/archive/refs/heads/DanGough/issue999.zip

**Comment by DanGough** [comment]
There are now Pester tests for various use cases of Execute-ProcessAsUser and Set-ActiveSetup.

- RunHidden.vbs has been simplified. There is no need to escape metacharacters in here, it was just breaking the commands. Escaping of metacharacters with cmd.exe should be left to the user, EXCEPT when they just supply a .cmd / .bat file that has one of these characters in the name. RegEx replace now does this for such filenames.
- To stop vbscript dropping the quotes from the supplied args, they are swapped for a placeholder [{quote}] which is then turned back to " inside the .vbs.
- Quoting of cmd.exe args changed to ensure they are in the format cmd.exe /c ""path to file.cmd" arg1 "arg 2" arg3"

**Review by sintaxasn — APPROVED** [review]
Great work on this!

**Review by mmashwani — APPROVED** [review]
Nice, looks good!

**Comment by DanGough** [comment]
Small extra code cleanup + a couple more test cases, all tests still passing.

**Comment by IREJDW** [comment]
Hi 


Git Stubpath
if brackets occur in a variable such as env:Programfiles(x86), ^ characters are generated in the registry in the StubPath Value. See screenshots.

**Comment by IREJDW** [comment]
you can test it with:
$StubExePath= "C:\()"
StubExePath = $StubExePath -replace '([()%!^&])', '^$1

Output of $StubExePath:
C:\^(^)

**Comment by DanGough** [comment]
This was done When passing certain characters on the command line to cmd.exe, the characters ()%!^& have to be pre-fixed with ^ in order to work. However, I believe you do not need to do this if they are between double quotes, so I will take another look at this.

e.g. the brackets here would need to be escaped:

`cmd.exe /c IF EXIST file.txt ^(do something^)`

But these would not:

`cmd.exe /c del "C:\Program Files (x86)\file.txt"`

**Comment by DanGough** [comment]
> Hi
> 
> Git Stubpath if brackets occur in a variable such as env:Programfiles(x86), ^ characters are generated in the registry in the StubPath Value. See screenshots. However, it works with env:Programfiles.

It turns out that brackets need to be escaped only if there is no space in the path. If there is a space, cmd.exe handles it differently and does not require brackets to be escaped, hence why `Program Files (x86)` works just fine.

You may see that `C:\Temp\Test(1).cmd` would need to be escaped to `C:\Temp\Test^(1^).cmd`, yet `C:\Temp\Test (1).cmd` would not!

One small further change pushed to Develop branch to correct this:

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/b2351b0d64f18686d699a0f111be15cd44a5a60f

**Comment by IREJDW** [comment]
Hello everyone,

the last adjustment seems to work now. I will test it but will not be able to do so for the next few days.

Thanks for the fix

**Pull request merged**
