### PR TITLE
fixes for PSADT issues #275 #276 #278

### PR DESCRIPTION
**Pull request by That-Annoying-Guy**
All the changes are described in #275 #276 #278

BTW: This is the first time I'm using the Fork/Pull_Request from GitHub. If there is a better way to submit fixes to you guys (Like using branch(?)) I'll try to do that next time.

### CODE REVIEW

**Comment by amotaz** [comment]
Nope, this is good. I'm going to review the code and get back to you soon. Thank you

**Comment by That-Annoying-Guy** [comment]
I just realized that Show-InstallationPrompt has the same logging problem. -DisableLogging needs to be added the same way:

`			Start-Process -FilePath "$PSHOME\powershell.exe" -ArgumentList "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -File `"$scriptPath`" -ReferredInstallTitle `"$Title`" -ReferredInstallName `"$installName`" -ReferredLogName `"$logName`" -ShowInstallationPrompt $installPromptParameters -AsyncToolkitLaunch -DisableLogging" -WindowStyle 'Hidden' -ErrorAction 'SilentlyContinue'`

Can I update my fork without redoing the pull request?

**Comment by That-Annoying-Guy** [comment]
I just realized that Show-InstallationPrompt has the same logging problem. -DisableLogging needs to be added the same way:

`			Start-Process -FilePath "$PSHOME\powershell.exe" -ArgumentList "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -File `"$scriptPath`" -ReferredInstallTitle `"$Title`" -ReferredInstallName `"$installName`" -ReferredLogName `"$logName`" -ShowInstallationPrompt $installPromptParameters -AsyncToolkitLaunch -DisableLogging" -WindowStyle 'Hidden' -ErrorAction 'SilentlyContinue'`

I also noted that -AsyncToolkitLaunch will compress the log files of the parent script.
And that Exit-script does not handle MSI error 1702 0r 1732

I updated my fork. Do I have to redo the pull request?

**Comment by sintaxasn** [comment]
This issue was moved to https://discourse.psappdeploytoolkit.com/t/fixes-for-psadt-issues-275-276-278/1198

**Pull request closed without merging**
