### PR TITLE
precompiled cs as wdac audit enable breaks ADT

### PR DESCRIPTION
**Pull request by Numidian**
as per wdac issue https://discourse.psappdeploytoolkit.com/t/appdeploytoolkitmain-cs-could-not-be-opened/2962/5

can't relax security note sure if there is a better way to precompile AppDeployToolkitMain.cs, but precompile allows ADT to execute without relaxing the policy

Before submitting this Pull Request, I made sure:

- [X] I tested the toolkit with my changes and made sure it doesn't break other code.

- [X] I updated the documentation with the changes I made.

- [X] The code I changed has comments with explanation.

- [X] The encoding of the file wasn't changed. It is still UTF8 with BOM.

### CODE REVIEW

**Comment by DanGough** [comment]
I understand there are already plans to work around this issue. Also the dll should ideally be compiled and signed during a build process rather than checking in the binary as source.

**Comment by pvwc** [comment]
Is there any timeline for when a fix for this issue will be applied ?

**Comment by Ath3na-UK** [comment]
Also just come across this as implementing WDAC, good to know its being looked at.

**Comment by mjr4077au** [comment]
The issue this problem tries to address has been resolved for the upcoming PSADT v4 release. As such, I'll close this; but thank you for your contribution!

**Pull request closed without merging**
