### PR TITLE
Mask Passwords in logs: AppDeployToolkitMain.ps1

### PR DESCRIPTION
**Pull request by AntoineRv**
Mask passwords showed as command line in logs.
Parameters triggered : 
-Password
-Pwd
-Passwords
-Pwds

Before submitting this Pull Request, I made sure:

- [X] I tested the toolkit with my changes and made sure it doesn't break other code.

- [X] I updated the documentation with the changes I made.

- [X] The code I changed has comments with explanation.

- [X] The encoding of the file wasn't changed. It is still UTF8 with BOM.

### CODE REVIEW

**Comment by mjr4077au** [comment]
Wouldn't it be better on your side to use `[System.Security.SecureString]` objects rather than passing plain-text passwords around in RAM and then trying to mask them out?

**Comment by AntoineRv** [comment]
Hello,


Thanks for reply.
I will try it. But not everyone is knowing this type of object.
It could be well to implement this feature.

**Comment by DanGough** [comment]
This looks like it overwrites the contents of an existing internal toolkit variable $deployAppScriptParameters, which is used elsewhere in the code.

It would be better to implement password masking in a more generic fashion directly inside Write-Log.

**Comment by AntoineRv** [comment]
> This looks like it overwrites the contents of an existing internal toolkit variable $deployAppScriptParameters, which is used elsewhere in the code.
> 
> It would be better to implement password masking in a more generic fashion directly inside Write-Log.

Yes it overwrites the contents of variable $deployAppScriptParameters.
You're right to implement it inside Write-Log.

**Comment by DanGough** [comment]
Ok, will close this for now, as all efforts for new enhancements are going towards 4.0 which will look pretty different to v3.

But we should have a suggestion for this filed under Issues so that it doesn't get forgotten about!

**Pull request closed without merging**
