### PR TITLE
Formatting updates to documentation

### PR DESCRIPTION
**Pull request by lboening**
Removed extra spaces before colons in function area. Changed spelling of a few words.

### CODE REVIEW

**Comment by lboening** [comment]
Should I remove my simple test? The intention is to correct the word document.

**Comment by mmashwani** [comment]
Yeah, remove the simple test for now. If you get that fleshed out, I would be more then happy to accept the pull.

Submit the word document pull request and I'll merge it.

**Comment by lboening** [comment]
I will have to figure out how to remove the test. I can figure this out myself, I hope.

**Comment by mmashwani** [comment]
If you want, I can just accept the pull request and then delete the test myself. It's not a big deal.

**Comment by lboening** [comment]
Is there a chance you can just ignore and delete this merge request? I have removed the test from my local Git clone, but cannot figure out how to remove only the Test change from the pull request.

**Comment by mmashwani** [comment]
I've closed it. Same as deleting it for what we want.

**Comment by mmashwani** [comment]
Just submit a new pull request with the document and I'll merge it in.

**Pull request closed without merging**
