### PR TITLE
Update AppDeployToolkitMain.ps1

### PR DESCRIPTION
**Pull request by dianneman**
Fixed switch handling otherwise this function does not work when dot sourced.

Before submitting this PR, I made sure:

- [X] I tested the toolkit with my changes. Made sure it doesn't break other code.

- [X] I updated the documentation with the changes I made.

- [X] The code I changed has comments with explanation.

- [X] The encoding of the file wasn't changed. It is still UTF8 without BOM.

### CODE REVIEW

**Review by sintaxasn — APPROVED** [review]
Tested and this looks good. Thank you!

**Comment by sintaxasn** [comment]
> Fixed switch handling otherwise this function does not work when dot sourced.

So I can see this fixed the issue but I'm not exactly sure why. Do you mind explaining? I want to be sure we haven't introduced the same issue elsewhere, and that we are aware of the why, so we can avoid it in future. Thanks!

**Comment by dianneman** [comment]
No problem I should have done that. 
The object you use in switch will be the new current object and this object will only contain the types like int32,boolean because of .Value.GetType().Name

_PSItem
You can use the $PSItem or $_ to reference the current item that was processed. When we do a simple match, $PSItem is the value that we are matching. I'll be performing some advanced matches in the next section where this variable is used.
https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-switch?view=powershell-7.1_

**Comment by rmoreas** [comment]
Any idea when v3.8.5 will be released?

**Comment by wbatzle** [comment]
Is this fix going to be published? Looking to resolve this in our environment.

**Pull request merged**
